apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        -  name: my-container
           image: nginx
           ports:
            -  containerPort: 80
           volumeMounts:
           -  mountPath: "mnt/storage"
              name: my-volume
      volumes:
        -  name: my-volume
           persistentVolumeClaim:
            claimName: my-pvc
           
               
